import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=fs.existsSync('/app/public/v094-player-intel.js')?'/app':process.cwd();
const ui=fs.readFileSync(`${root}/public/v094-player-intel.js`,'utf8');
const pkg=JSON.parse(fs.readFileSync(`${root}/package.json`,'utf8'));
assert.match(ui,/function bullshooterIdForRow\(row\)/,'robustness must resolve the BullShooter cell directly');
assert.match(ui,/textContent\.trim\(\)\.toUpperCase\(\)==='BULLSHOOTER'/,'robustness must locate the BullShooter column by header, not numeric position');
assert.match(ui,/playerByBsId\.get\(bs\)/,'row mapping must use BullShooter ID as the primary key');
assert.match(ui,/row\.dataset\.bullshooterId=bs/,'resolved BullShooter ID should be cached on the row');
const fnStart=ui.indexOf('function playerForRow(row)');
const exact=ui.indexOf('playerByBsId.get(bs)',fnStart);
const cached=ui.indexOf('dataset?.nexusPlayerId',fnStart);
assert.ok(fnStart>=0&&exact>fnStart&&cached>exact,'BullShooter exact lookup must happen before stale row-cache/name fallback');
assert.doesNotMatch(ui,/const text=row\?\.textContent\|\|'',bs=\(text\.match/,'whole-row number scanning must not be the primary mapper');
assert.equal(pkg.version,'0.9.14');
console.log('V0.9.14 robustness mapping checks passed');
