import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=fs.existsSync('/app/server.js')?'/app':process.cwd();
const read=p=>fs.readFileSync(`${root}/${p}`,'utf8');
const server=read('server.js'),edc=read('src/edc.js'),playerUi=read('public/v094-player-intel.js'),identityUi=read('public/v0912-identity.js'),tocUi=read('public/v090.js'),robustUi=read('public/v0915-robustness.js'),html=read('public/index.html'),pkg=JSON.parse(read('package.json'));
assert.match(edc,/export function edcRecordKey\(/,'EDC records need semantic snapshot keys');
assert.match(edc,/recordKey:edcRecordKey\(r\)/,'loaded EDC records must expose recordKey');
assert.match(server,/recordKey:r\.recordKey\|\|edcRecordKey\(r\)/,'manual EDC link must persist recordKey');
assert.match(server,/candidates=same\.filter/,'EDC link must have semantic fallback instead of sourceRow-only linking');
assert.match(server,/req\.method==='DELETE'/,'unlink routes must remain available');
assert.match(playerUi,/recordKey:record\.recordKey\|\|''/,'main EDC link must send recordKey');
assert.match(playerUi,/Unlink EDC record/,'EDC unlink action must be explicit');
assert.match(playerUi,/window\.CDNexusRobustnessV0915\?\.refresh/,'legacy robustness renderer must delegate to V0.9.15');
assert.match(identityUi,/recordKey:eb\.dataset\.recordKey/,'RAW EDC linking must forward recordKey');
assert.match(tocUi,/Unlink this PPD\/TOC record/,'TOC unlink must require explicit confirmation');
assert.match(robustUi,/currentStatsDiagnostics\?\.x01Count/,'robustness must use BullShooter X01 evidence');
assert.match(robustUi,/currentStatsDiagnostics\?\.cricketCount/,'robustness must use BullShooter Cricket evidence');
assert.match(robustUi,/h\.textContent\.trim\(\)\.toUpperCase\(\)==='BULLSHOOTER'/,'robustness must map rows by the actual BullShooter column');
assert.match(robustUi,/state\.byBs\.get\(id\)/,'BullShooter ID must be the primary robustness lookup');
assert.match(robustUi,/state\.observer\.observe\(body,\{childList:true\}\)/,'robustness observer must not watch its own subtree mutations');
assert.match(html,/v0915-robustness\.js/,'V0.9.15 robustness module must load');
assert.equal(pkg.version,'0.9.15');
console.log('V0.9.15 stable EDC linking, unlink and robustness checks passed');
