import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=fs.existsSync('/app/src/dartstoc.js')?'/app':process.cwd();
const toc=fs.readFileSync(`${root}/src/dartstoc.js`,'utf8');
assert.match(toc,/const unique=new Map\(\)/,'incremental TOC persistence must deduplicate each write set');
assert.match(toc,/unique\.set\(row\.tocId,chooseBetterRecord\(unique\.get\(row\.tocId\),row\)\)/,'duplicate TOC IDs must collapse to one best record before upsert');
assert.match(toc,/const deduped=\[\.\.\.unique\.values\(\)\]/,'Supabase batches must be built from deduplicated rows');
assert.match(toc,/for\(let i=0;i<deduped\.length;i\+=100\)/,'incremental Supabase writes must batch the deduplicated set');
assert.match(toc,/return deduped\.length/,'progress metadata must count durable unique rows, not duplicate source rows');
console.log('TOC progressive dedupe regression checks passed');
