import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync('public/tournament.html','utf8');
const collab=fs.readFileSync('public/tournament-v125-collab.js','utf8');
const staging=fs.readFileSync('src/tournament-staging-server.mjs','utf8');
const server=fs.readFileSync('server.js','utf8');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
assert.ok(html.includes('/tournament-v125-collab.js'),'main Tournament Director must load V0.12.5 collaboration client');
assert.ok(collab.includes('editKeyRequired=backend.editKeyRequired!==false'),'client must support keyed staging and authenticated main collaboration');
assert.ok(collab.includes('setInterval(()=>pullRemote(false),2500)'),'director collaboration must poll remote state');
assert.ok(collab.includes("editKeyRequired?'Live shared staging':'Live NEXUS sync'"),'client must identify live main sync');
assert.ok(staging.includes("type=eq.tournament-staging"),'collaborative staging must be scoped to tournament-staging rows');
assert.ok(staging.includes('Player-directory writes are disabled on collaborative staging.'),'collaborative staging must not write NEXUS players');
assert.ok(staging.includes("x-tournament-edit-key"),'staging director writes must require per-tournament edit key');
assert.ok(server.indexOf('tdPublicMatch') < server.indexOf('if(!requireAuth(req,res))return;'),'public tournament snapshot must remain outside auth');
assert.ok(server.indexOf("tdSnapshotMatch&&req.method==='GET'") > server.indexOf('if(!requireAuth(req,res))return;'),'full tournament state GET must remain authenticated');
assert.ok(server.includes('getTournamentDirectorSnapshot'),'main server must load full tournament snapshots for collaboration');
assert.ok(server.includes('collaborative:true,editKeyRequired:false,playerWrites:true'),'main NEXUS collaboration must use existing authentication rather than staging edit keys');
assert.equal(pkg.version,'0.11.3','Tournament Director must preserve global NEXUS package version');
console.log('Tournament Director V0.12.5 collaboration contract tests passed');
