import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync('public/tournament.html','utf8');
const enhancements=fs.readFileSync('public/tournament-enhancements.js','utf8');
const finalize=fs.readFileSync('public/tournament-v123-finalize.js','utf8');
const publicJs=fs.readFileSync('public/tournament-public.js','utf8');
const api=fs.readFileSync('src/tournament-director-api.js','utf8');
const server=fs.readFileSync('server.js','utf8');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
for(const text of ['tdOpenCalendar','tdRecurrenceEnabled','tdFlyerFile','tdSponsorName','tdManagedVenue','tdAddedMoney','tdBountyEnabled','tdManualBullshooter','tdManualAddToNexus','tdAvoidFF','tdFeatForm','Tonight\'s Mystery Out Number','tdTripsEnabled'])assert.ok(html.includes(text),`missing V0.12.3 UI contract: ${text}`);
assert.ok(html.includes('tournament-v123-finalize.js'),'final safety module must load');
assert.ok(enhancements.includes("/api/tournament-director/players"),'walk-in NEXUS capture endpoint missing');
assert.ok(enhancements.includes('avoidFemaleFemale'),'gender-aware draw rule missing');
assert.ok(enhancements.includes('td-out-names'),'Mystery Out player labels missing');
assert.ok(finalize.includes('sanitizedPublicSnapshot'),'portable public links must be sanitized');
assert.ok(finalize.includes("`entrant-${i+1}`"),'portable public participant IDs must be remapped');
assert.ok(finalize.includes('autoRollCompleted'),'rolling side pots must auto-carry on completion');
assert.ok(finalize.includes('Other Mini-Game Pots'),'generic mini-game pot support missing');
assert.ok(publicJs.includes("/api/tournament-director/snapshots/"),'public page live snapshot route missing');
assert.ok(api.includes('camarillo_competitions'),'database autosave target missing');
assert.ok(api.includes('camarillo_players'),'NEXUS player capture target missing');
assert.ok(api.includes('entrantIdMap'),'server public snapshots must remap internal entrant IDs');
assert.ok(server.indexOf('tdPublicMatch') < server.indexOf('if(!requireAuth(req,res))return;'),'public tournament GET must be before auth');
assert.ok(server.includes("url.pathname==='/api/tournament-director/players'"),'authenticated player capture route missing');
assert.equal(pkg.version,'0.11.3','Tournament Director must preserve global NEXUS package version');
console.log('Tournament Director V0.12.3 contract tests passed');
