import fs from 'node:fs';
import assert from 'node:assert/strict';
import {publicTournamentDirectorSnapshot} from '../src/tournament-director-api.js';
const boardboss=fs.readFileSync('public/tournament-v124-boardboss.js','utf8');
const myHtml=fs.readFileSync('public/tournament-my.html','utf8');
const myJs=fs.readFileSync('public/tournament-my.js','utf8');
const publicV124=fs.readFileSync('public/tournament-v124-public.js','utf8');
const finalize=fs.readFileSync('public/tournament-v123-finalize.js','utf8');
const manifest=JSON.parse(fs.readFileSync('public/tournament-manifest.webmanifest','utf8'));
for(const text of ['My View','Restore Points','Correct Bracket','Director Analytics','createRestore','reopenResult','directorHistory','bigScreenUrl'])assert.ok(boardboss.includes(text),`missing V0.12.4 feature: ${text}`);
assert.ok(finalize.includes('tournament-v124-boardboss.js'),'V0.12.4 director module must load');
assert.ok(myHtml.includes('Enable Match Alerts')&&myHtml.includes('Your Matches'),'player My View surface missing');
assert.ok(myJs.includes('showNotification')&&myJs.includes('availableMatches'),'My View alert/readiness logic missing');
assert.ok(publicV124.includes('mode')&&publicV124.includes('My View'),'public big-screen/My View launcher missing');
assert.equal(manifest.display,'standalone','Tournament Director should be installable as a standalone PWA');
const state={extensions:{tournamentId:'secret-tournament',event:{},finance:{},feats:[]},meta:{name:'Test',format:'double',entrantMode:'blind-doubles',boardCount:2},roster:[{id:'internal-a',name:'Alice',gender:'female',email:'alice@example.com',bullshooterId:'BS123'},{id:'internal-b',name:'Bob',gender:'male'}],bracketEntrants:[{id:'team:private-team',name:'Alice + Bob',seed:1,memberIds:['internal-a','internal-b']}],resultHistory:[],boardAssignments:{},mystery:{hits:[]},updatedAt:new Date().toISOString()};
const pub=publicTournamentDirectorSnapshot(state),json=JSON.stringify(pub);
assert.equal(pub.publicPlayers.length,2,'public snapshot should expose privacy-safe player identities');
assert.equal(pub.publicPlayers[0].entrantId,'entrant-1','player should map to sanitized entrant');
assert.ok(!json.includes('internal-a')&&!json.includes('private-team'),'public snapshot must not expose internal participant IDs');
assert.ok(!json.includes('alice@example.com')&&!json.includes('BS123'),'public snapshot must not expose contact or BullShooter IDs');
console.log('Tournament Director V0.12.4 BoardBoss-inspired contract tests passed');
