import fs from 'node:fs';

const bsPath = fs.existsSync('/app/src/bullshooter.js') ? '/app/src/bullshooter.js' : 'src/bullshooter.js';
let s = fs.readFileSync(bsPath, 'utf8');
s = s.replace("const PARSER_VERSION = '0.7.5';", "const PARSER_VERSION = '0.7.6';");

const anchor = `function recentAvg(rows, n) {\n  const vals = rows.slice(0, n).map(r => r.stat).filter(Number.isFinite);\n  return vals.length ? round(average(vals), 2) : null;\n}\n`;
const insert = `function numbersIn(text) {\n  return (String(text || '').replace(/,/g, '').match(/-?\\d+(?:\\.\\d+)?/g) || []).map(Number);\n}\n\nfunction valueAtOrNear(lines, pattern, min, max) {\n  for (let i = 0; i < lines.length; i++) {\n    if (!pattern.test(lines[i])) continue;\n    const local = numbersIn(lines[i]).find(v => inRange(v, min, max));\n    if (Number.isFinite(local)) return local;\n    for (const d of [1,2,3]) {\n      for (const j of [i + d, i - d]) {\n        if (j < 0 || j >= lines.length) continue;\n        const value = numbersIn(lines[j]).find(v => inRange(v, min, max));\n        if (Number.isFinite(value)) return value;\n      }\n    }\n  }\n  return null;\n}\n\nfunction parseRecentPerformanceText(text) {\n  const lines = String(text || '').split(/\\n+/).map(x => x.trim()).filter(Boolean);\n  return {\n    mpr: valueAtOrNear(lines, /(?:Cricket\\s*)?MPR/i, 0.5, 9),\n    ppd: valueAtOrNear(lines, /(?:01\\s*)?PPD/i, 5, 100)\n  };\n}\n\nasync function recentPerformanceSample(page, sampleSize) {\n  const selects = page.locator('select');\n  const count = await selects.count();\n  for (let i = 0; i < count; i++) {\n    const sel = selects.nth(i);\n    if (!(await sel.isVisible().catch(() => false))) continue;\n    const context = await sel.evaluate(el => {\n      let p = el.parentElement;\n      for (let depth = 0; p && depth < 6; depth++, p = p.parentElement) {\n        const text = (p.innerText || '').trim();\n        if (/Recent Performance/i.test(text) && /sample size/i.test(text)) return text;\n      }\n      return '';\n    }).catch(() => '');\n    if (!context) continue;\n    const options = await sel.locator('option').evaluateAll(opts => opts.map(o => ({value:o.value,text:(o.textContent||'').trim()}))).catch(() => []);\n    const option = options.find(o => Number((o.text.match(/\\d+/)||[])[0]) === sampleSize);\n    if (!option) continue;\n    await sel.selectOption(option.value).catch(() => {});\n    await page.waitForTimeout(900);\n    const updated = await sel.evaluate(el => {\n      let p = el.parentElement;\n      for (let depth = 0; p && depth < 6; depth++, p = p.parentElement) {\n        const text = (p.innerText || '').trim();\n        if (/Recent Performance/i.test(text) && /sample size/i.test(text)) return text;\n      }\n      return '';\n    }).catch(() => '');\n    const parsed = parseRecentPerformanceText(updated || context);\n    return {...parsed, sampleSize};\n  }\n  return {mpr:null, ppd:null, sampleSize:null};\n}\n\n${anchor}`;
if (!s.includes(anchor)) throw new Error('V0.7.6 patch: recentAvg anchor not found');
s = s.replace(anchor, insert);

const oldBlock = `    const { profile } = await waitForCoreStats(page, id);\n    const cricketGames = await collectRecent(page, 'cricket', 30).catch(() => []);\n    await loadProfilePage(page, url);\n    const games01 = await collectRecent(page, '01', 30).catch(() => []);\n    profile.recentCricketGames = cricketGames;\n    profile.recent01Games = games01;\n    profile.last30MPR = recentAvg(cricketGames, 30);\n    profile.last10MPR = recentAvg(cricketGames, 10);\n    profile.last30PPD = recentAvg(games01, 30);\n    profile.last10PPD = recentAvg(games01, 10);`;
const newBlock = `    const { profile } = await waitForCoreStats(page, id);\n    const recent30 = await recentPerformanceSample(page, 30).catch(() => ({mpr:null,ppd:null,sampleSize:null}));\n    const recent10 = await recentPerformanceSample(page, 10).catch(() => ({mpr:null,ppd:null,sampleSize:null}));\n    await loadProfilePage(page, url);\n    const cricketGames = await collectRecent(page, 'cricket', 30).catch(() => []);\n    await loadProfilePage(page, url);\n    const games01 = await collectRecent(page, '01', 30).catch(() => []);\n    profile.recentCricketGames = cricketGames;\n    profile.recent01Games = games01;\n    profile.last30MPR = Number.isFinite(recent30.mpr) ? recent30.mpr : (cricketGames.length >= 30 ? recentAvg(cricketGames, 30) : null);\n    profile.last10MPR = Number.isFinite(recent10.mpr) ? recent10.mpr : (cricketGames.length >= 10 ? recentAvg(cricketGames, 10) : null);\n    profile.last30PPD = Number.isFinite(recent30.ppd) ? recent30.ppd : (games01.length >= 30 ? recentAvg(games01, 30) : null);\n    profile.last10PPD = Number.isFinite(recent10.ppd) ? recent10.ppd : (games01.length >= 10 ? recentAvg(games01, 10) : null);\n    profile.last30SampleSize = recent30.sampleSize;\n    profile.last10SampleSize = recent10.sampleSize;\n    profile.recentPerformanceSource = (recent30.sampleSize || recent10.sampleSize) ? 'bullshooter-recent-performance' : 'recent-game-table';`;
if (!s.includes(oldBlock)) throw new Error('V0.7.6 patch: importer assignment block not found');
s = s.replace(oldBlock, newBlock);
fs.writeFileSync(bsPath, s);

const serverPath = fs.existsSync('/app/server.js') ? '/app/server.js' : 'server.js';
let server = fs.readFileSync(serverPath, 'utf8');
server = server.replaceAll("version:'0.7.5'", "version:'0.7.6'");
server = server.replaceAll('Camarillo Darts V0.7.5 running', 'Camarillo Darts V0.7.6 running');
fs.writeFileSync(serverPath, server);

const indexPath = fs.existsSync('/app/public/index.html') ? '/app/public/index.html' : 'public/index.html';
let html = fs.readFileSync(indexPath, 'utf8');
html = html.replaceAll('V0.7.5', 'V0.7.6');
html = html.replaceAll('Camarillo Darts V0.7.5', 'Camarillo Darts V0.7.6');
fs.writeFileSync(indexPath, html);
