import fs from 'node:fs';

const bsPath = fs.existsSync('/app/src/bullshooter.js') ? '/app/src/bullshooter.js' : 'src/bullshooter.js';
let s = fs.readFileSync(bsPath, 'utf8');
s = s.replace("const PARSER_VERSION = '0.7.6';", "const PARSER_VERSION = '0.7.7';");

const oldRecent = `async function recentPerformanceSample(page, sampleSize) {\n  const selects = page.locator('select');\n  const count = await selects.count();\n  for (let i = 0; i < count; i++) {\n    const sel = selects.nth(i);\n    if (!(await sel.isVisible().catch(() => false))) continue;\n    const context = await sel.evaluate(el => {\n      let p = el.parentElement;\n      for (let depth = 0; p && depth < 6; depth++, p = p.parentElement) {\n        const text = (p.innerText || '').trim();\n        if (/Recent Performance/i.test(text) && /sample size/i.test(text)) return text;\n      }\n      return '';\n    }).catch(() => '');\n    if (!context) continue;\n    const options = await sel.locator('option').evaluateAll(opts => opts.map(o => ({value:o.value,text:(o.textContent||'').trim()}))).catch(() => []);\n    const option = options.find(o => Number((o.text.match(/\\d+/)||[])[0]) === sampleSize);\n    if (!option) continue;\n    await sel.selectOption(option.value).catch(() => {});\n    await page.waitForTimeout(900);\n    const updated = await sel.evaluate(el => {\n      let p = el.parentElement;\n      for (let depth = 0; p && depth < 6; depth++, p = p.parentElement) {\n        const text = (p.innerText || '').trim();\n        if (/Recent Performance/i.test(text) && /sample size/i.test(text)) return text;\n      }\n      return '';\n    }).catch(() => '');\n    const parsed = parseRecentPerformanceText(updated || context);\n    return {...parsed, sampleSize};\n  }\n  return {mpr:null, ppd:null, sampleSize:null};\n}`;

const newRecent = `async function recentPerformanceSample(page, sampleSize) {\n  const selects = page.locator('select');\n  const count = await selects.count();\n  for (let i = 0; i < count; i++) {\n    const sel = selects.nth(i);\n    if (!(await sel.isVisible().catch(() => false))) continue;\n    const meta = await sel.evaluate(el => {\n      let p = el.parentElement;\n      for (let depth = 0; p && depth < 8; depth++, p = p.parentElement) {\n        const text = (p.innerText || '').trim();\n        if (/Recent Performance/i.test(text) && /sample size/i.test(text)) return {found:true};\n      }\n      return {found:false};\n    }).catch(() => ({found:false}));\n    if (!meta.found) continue;\n    const options = await sel.locator('option').evaluateAll(opts => opts.map(o => ({value:o.value,text:(o.textContent||'').trim()}))).catch(() => []);\n    const option = options.find(o => Number((o.text.match(/\\d+/)||[])[0]) === sampleSize);\n    if (!option) return {mpr:null,ppd:null,sampleSize:null,availableSamples:options.map(o=>o.text)};\n    await sel.selectOption(option.value);\n    await page.waitForTimeout(1200);\n    const cleaned = await sel.evaluate(el => {\n      let p = el.parentElement;\n      let target = null;\n      for (let depth = 0; p && depth < 8; depth++, p = p.parentElement) {\n        const text = (p.innerText || '').trim();\n        if (/Recent Performance/i.test(text) && /sample size/i.test(text) && /MPR/i.test(text) && /PPD/i.test(text)) { target = p; break; }\n      }\n      if (!target) return '';\n      const clone = target.cloneNode(true);\n      clone.querySelectorAll('select,option,script,style,noscript').forEach(n => n.remove());\n      return (clone.innerText || '').trim();\n    }).catch(() => '');\n    const parsed = parseRecentPerformanceText(cleaned);\n    return {...parsed, sampleSize, rawRecentPerformanceText:cleaned};\n  }\n  return {mpr:null, ppd:null, sampleSize:null};\n}`;
if (!s.includes(oldRecent)) throw new Error('V0.7.7 patch: V0.7.6 recentPerformanceSample not found');
s = s.replace(oldRecent, newRecent);

const oldBlock = `    const { profile } = await waitForCoreStats(page, id);\n    const recent30 = await recentPerformanceSample(page, 30).catch(() => ({mpr:null,ppd:null,sampleSize:null}));\n    const recent10 = await recentPerformanceSample(page, 10).catch(() => ({mpr:null,ppd:null,sampleSize:null}));\n    await loadProfilePage(page, url);\n    const cricketGames = await collectRecent(page, 'cricket', 30).catch(() => []);\n    await loadProfilePage(page, url);\n    const games01 = await collectRecent(page, '01', 30).catch(() => []);\n    profile.recentCricketGames = cricketGames;\n    profile.recent01Games = games01;\n    profile.last30MPR = Number.isFinite(recent30.mpr) ? recent30.mpr : (cricketGames.length >= 30 ? recentAvg(cricketGames, 30) : null);\n    profile.last10MPR = Number.isFinite(recent10.mpr) ? recent10.mpr : (cricketGames.length >= 10 ? recentAvg(cricketGames, 10) : null);\n    profile.last30PPD = Number.isFinite(recent30.ppd) ? recent30.ppd : (games01.length >= 30 ? recentAvg(games01, 30) : null);\n    profile.last10PPD = Number.isFinite(recent10.ppd) ? recent10.ppd : (games01.length >= 10 ? recentAvg(games01, 10) : null);\n    profile.last30SampleSize = recent30.sampleSize;\n    profile.last10SampleSize = recent10.sampleSize;\n    profile.recentPerformanceSource = (recent30.sampleSize || recent10.sampleSize) ? 'bullshooter-recent-performance' : 'recent-game-table';`;
const newBlock = `    const { profile } = await waitForCoreStats(page, id);\n    const recent50 = await recentPerformanceSample(page, 50).catch(() => ({mpr:null,ppd:null,sampleSize:null}));\n    const recent20 = await recentPerformanceSample(page, 20).catch(() => ({mpr:null,ppd:null,sampleSize:null}));\n    const recent10 = await recentPerformanceSample(page, 10).catch(() => ({mpr:null,ppd:null,sampleSize:null}));\n    await loadProfilePage(page, url);\n    const cricketGames = await collectRecent(page, 'cricket', 30).catch(() => []);\n    await loadProfilePage(page, url);\n    const games01 = await collectRecent(page, '01', 30).catch(() => []);\n    profile.recentCricketGames = cricketGames;\n    profile.recent01Games = games01;\n    profile.last50MPR = Number.isFinite(recent50.mpr) ? recent50.mpr : null;\n    profile.last50PPD = Number.isFinite(recent50.ppd) ? recent50.ppd : null;\n    profile.last20MPR = Number.isFinite(recent20.mpr) ? recent20.mpr : null;\n    profile.last20PPD = Number.isFinite(recent20.ppd) ? recent20.ppd : null;\n    profile.last10MPR = Number.isFinite(recent10.mpr) ? recent10.mpr : null;\n    profile.last10PPD = Number.isFinite(recent10.ppd) ? recent10.ppd : null;\n    profile.last50SampleSize = recent50.sampleSize;\n    profile.last20SampleSize = recent20.sampleSize;\n    profile.last10SampleSize = recent10.sampleSize;\n    profile.last30MPR = null; profile.last30PPD = null; profile.last30SampleSize = null;\n    profile.recentPerformanceSource = 'bullshooter-recent-performance';\n    profile.recentPerformanceSamples = {50:recent50,20:recent20,10:recent10};`;
if (!s.includes(oldBlock)) throw new Error('V0.7.7 patch: V0.7.6 importer block not found');
s = s.replace(oldBlock, newBlock);
fs.writeFileSync(bsPath, s);

const serverPath = fs.existsSync('/app/server.js') ? '/app/server.js' : 'server.js';
let server = fs.readFileSync(serverPath, 'utf8');
server = server.replaceAll("version:'0.7.6'", "version:'0.7.7'");
server = server.replaceAll('Camarillo Darts V0.7.6 running', 'Camarillo Darts V0.7.7 running');
fs.writeFileSync(serverPath, server);

const indexPath = fs.existsSync('/app/public/index.html') ? '/app/public/index.html' : 'public/index.html';
let html = fs.readFileSync(indexPath, 'utf8');
html = html.replaceAll('V0.7.6', 'V0.7.7');
html = html.replaceAll('Camarillo Darts V0.7.6', 'Camarillo Darts V0.7.7');
html = html.replace('<script src="/v075.js"></script>', '<script src="/v077.js"></script>');
fs.writeFileSync(indexPath, html);
