import fs from 'node:fs';
const serverPath=fs.existsSync('/app/server.js')?'/app/server.js':'server.js';let server=fs.readFileSync(serverPath,'utf8');
server=server.replaceAll("version:'0.7.11'","version:'0.8.0'").replaceAll('Camarillo Darts V0.7.11 running','Camarillo Darts V0.8.0 running');
const marker="  if(url.pathname==='/api/feats'&&req.method==='GET')";
if(!server.includes('/api/league')){
 const routes=`  if(url.pathname==='/api/league'&&req.method==='GET'){const L=await import('./src/league.js');return json(res,200,await L.leagueSnapshot())}\n  if(url.pathname==='/api/league'&&req.method==='POST'){const L=await import('./src/league.js');return json(res,201,await L.createLeague(await body(req)))}\n  m=matchPath(url,/^\\/api\\/league\\/([^/]+)$/);if(m&&req.method==='PATCH'){const L=await import('./src/league.js');return json(res,200,await L.updateLeague(m[0],await body(req)))}\n  m=matchPath(url,/^\\/api\\/league\\/([^/]+)\\/teams$/);if(m&&req.method==='POST'){const L=await import('./src/league.js');return json(res,201,await L.createTeam(m[0],await body(req)))}\n  m=matchPath(url,/^\\/api\\/league\\/teams\\/([^/]+)$/);if(m&&req.method==='PATCH'){const L=await import('./src/league.js');return json(res,200,await L.updateTeam(m[0],await body(req)))}\n  m=matchPath(url,/^\\/api\\/league\\/([^/]+)\\/registrations$/);if(m&&req.method==='POST'){const L=await import('./src/league.js');return json(res,201,await L.register(m[0],await body(req)))}\n  m=matchPath(url,/^\\/api\\/league\\/registrations\\/([^/]+)$/);if(m&&req.method==='PATCH'){const L=await import('./src/league.js');return json(res,200,await L.updateRegistration(m[0],await body(req)))}\n  m=matchPath(url,/^\\/api\\/league\\/([^/]+)\\/schedule$/);if(m&&req.method==='POST'){const L=await import('./src/league.js');return json(res,200,await L.generateSchedule(m[0],await body(req)))}\n  m=matchPath(url,/^\\/api\\/league\\/matches\\/([^/]+)$/);if(m&&req.method==='PATCH'){const L=await import('./src/league.js');return json(res,200,await L.updateFixture(m[0],await body(req)))}\n  m=matchPath(url,/^\\/api\\/league\\/([^/]+)\\/standings$/);if(m&&req.method==='GET'){const L=await import('./src/league.js');return json(res,200,await L.standings(m[0]))}\n  m=matchPath(url,/^\\/api\\/league\\/([^/]+)\\/playoffs$/);if(m&&req.method==='POST'){const L=await import('./src/league.js');return json(res,200,await L.generatePlayoffs(m[0],await body(req)))}\n  m=matchPath(url,/^\\/api\\/league\\/([^/]+)\\/director$/);if(m&&req.method==='GET'){const L=await import('./src/league.js');return json(res,200,await L.directorDashboard(m[0]))}\n\n`;
 if(!server.includes(marker))throw new Error('V0.8 server insertion marker not found');server=server.replace(marker,routes+marker);
}
fs.writeFileSync(serverPath,server);
const indexPath=fs.existsSync('/app/public/index.html')?'/app/public/index.html':'public/index.html';let html=fs.readFileSync(indexPath,'utf8');html=html.replaceAll('V0.7.11','V0.8.0').replaceAll('Camarillo Darts V0.7.11','Camarillo Darts V0.8.0');if(!html.includes('/v080.css'))html=html.replace('</head>','<link rel="stylesheet" href="/v080.css"></head>');if(!html.includes('/v080.js'))html=html.replace('</body>','<script src="/v080.js"></script></body>');fs.writeFileSync(indexPath,html);
