import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';

const DB_PATH=process.env.TOURNAMENT_DB_PATH||path.join(path.dirname(process.env.DB_PATH||'data/db.json'),'tournaments.json');
const uid=p=>`${p}_${crypto.randomUUID()}`;
const now=()=>new Date().toISOString();
const fresh=()=>({version:1,events:[],entrants:[],teams:[],matches:[],series:[],audit:[]});
async function load(){try{return {...fresh(),...JSON.parse(await fs.readFile(DB_PATH,'utf8'))}}catch(e){if(e.code!=='ENOENT')throw e;return fresh()}}
async function save(db){await fs.mkdir(path.dirname(DB_PATH),{recursive:true});await fs.writeFile(DB_PATH,JSON.stringify(db,null,2));return db}
const clean=v=>String(v??'').trim();
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
function log(db,action,entityId,detail={}){db.audit.unshift({id:uid('audit'),at:now(),action,entityId,detail});db.audit=db.audit.slice(0,500)}
function shuffle(a){const out=[...a];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}

export async function snapshot(){return load()}
export async function createEvent(input={}){const db=await load();const boards=(input.boards||'1,2,3,4').toString().split(',').map(x=>clean(x)).filter(Boolean);const e={id:uid('event'),name:clean(input.name)||'Camarillo Darts Tournament',date:input.date||'',venue:clean(input.venue),format:input.format||'blind-draw-doubles',status:'setup',bestOf:num(input.bestOf,3),boards,pointsScheme:{first:10,second:7,third:5,fourth:3,participation:1},createdAt:now(),updatedAt:now()};db.events.push(e);log(db,'event.create',e.id,{name:e.name});await save(db);return e}
export async function updateEvent(id,patch={}){const db=await load(),e=db.events.find(x=>x.id===id);if(!e)throw new Error('Tournament not found');for(const k of ['name','date','venue','format','status','bestOf','boards'])if(k in patch)e[k]=patch[k];if(patch.pointsScheme)e.pointsScheme={...e.pointsScheme,...patch.pointsScheme};e.updatedAt=now();log(db,'event.update',id,patch);await save(db);return e}

export async function checkIn(eventId,playerId,extra={}){const db=await load();if(!db.events.some(x=>x.id===eventId))throw new Error('Tournament not found');let r=db.entrants.find(x=>x.eventId===eventId&&x.playerId===playerId);if(r){r.checkedIn=true;r.updatedAt=now()}else{r={id:uid('entry'),eventId,playerId,checkedIn:true,paid:!!extra.paid,notes:clean(extra.notes),createdAt:now()};db.entrants.push(r)}log(db,'entrant.checkin',r.id,{eventId,playerId});await save(db);return r}
export async function removeCheckIn(eventId,playerId){const db=await load();const r=db.entrants.find(x=>x.eventId===eventId&&x.playerId===playerId);if(!r)throw new Error('Entry not found');r.checkedIn=false;r.updatedAt=now();log(db,'entrant.checkout',r.id,{eventId,playerId});await save(db);return r}

function makeTeams(event,entrantIds){const shuffled=shuffle(entrantIds);if(event.format==='singles')return shuffled.map((p,i)=>({id:uid('team'),eventId:event.id,name:`Player ${i+1}`,playerIds:[p],seed:i+1,createdAt:now()}));if(event.format==='blind-draw-doubles'){const out=[];for(let i=0;i+1<shuffled.length;i+=2)out.push({id:uid('team'),eventId:event.id,name:`Team ${out.length+1}`,playerIds:[shuffled[i],shuffled[i+1]],seed:out.length+1,createdAt:now()});return out}throw new Error('Unsupported tournament format')}
function pairRound(teamIds,round){const out=[];for(let i=0;i<teamIds.length;i+=2){const a=teamIds[i]||null,b=teamIds[i+1]||null;if(!a&&!b)continue;out.push({id:uid('match'),round,slot:out.length+1,teamAId:a,teamBId:b,status:a&&b?'queued':'complete',winnerTeamId:a&&!b?a:b&&!a?b:null,scoreA:0,scoreB:0,board:'',startedAt:null,completedAt:a&&!b||b&&!a?now():null})}return out}
function assignBoards(db,eventId){const e=db.events.find(x=>x.id===eventId);if(!e)return;const active=db.matches.filter(x=>x.eventId===eventId&&x.status==='playing');const busy=new Set(active.map(x=>String(x.board)));const free=e.boards.filter(b=>!busy.has(String(b)));const queued=db.matches.filter(x=>x.eventId===eventId&&x.status==='queued').sort((a,b)=>a.round-b.round||a.slot-b.slot);for(const m of queued){const b=free.shift();if(!b)break;m.board=b;m.status='playing';m.startedAt=now()}}
function maybeAdvance(db,eventId){const e=db.events.find(x=>x.id===eventId);if(!e)return;let rounds=db.matches.filter(x=>x.eventId===eventId).map(x=>x.round);const round=Math.max(0,...rounds);const current=db.matches.filter(x=>x.eventId===eventId&&x.round===round);if(!current.length||current.some(x=>x.status!=='complete'))return;const winners=current.map(x=>x.winnerTeamId).filter(Boolean);if(winners.length===1){e.status='complete';e.championTeamId=winners[0];e.updatedAt=now();return}const next=pairRound(winners,round+1).map(m=>({...m,eventId}));db.matches.push(...next);assignBoards(db,eventId)}

export async function generateBracket(eventId,{redraw=false}={}){const db=await load(),e=db.events.find(x=>x.id===eventId);if(!e)throw new Error('Tournament not found');if(db.matches.some(x=>x.eventId===eventId)&&!redraw)throw new Error('Bracket already exists');if(redraw){db.teams=db.teams.filter(x=>x.eventId!==eventId);db.matches=db.matches.filter(x=>x.eventId!==eventId)}const entrants=db.entrants.filter(x=>x.eventId===eventId&&x.checkedIn).map(x=>x.playerId);const min=e.format==='singles'?2:4;if(entrants.length<min)throw new Error(`Need at least ${min} checked-in players`);if(e.format==='blind-draw-doubles'&&entrants.length%2)throw new Error('Blind draw doubles needs an even number of checked-in players');const teams=makeTeams(e,entrants);db.teams.push(...teams);const order=shuffle(teams.map(x=>x.id));const matches=pairRound(order,1).map(m=>({...m,eventId}));db.matches.push(...matches);e.status='running';e.updatedAt=now();assignBoards(db,eventId);maybeAdvance(db,eventId);log(db,'bracket.generate',eventId,{teams:teams.length,matches:matches.length});await save(db);return director(eventId,db)}

export async function reportResult(matchId,input={}){const db=await load(),m=db.matches.find(x=>x.id===matchId);if(!m)throw new Error('Match not found');if(!m.teamAId||!m.teamBId)throw new Error('Bye match does not need a result');const a=num(input.scoreA),b=num(input.scoreB);if(a===b)throw new Error('Tournament match cannot end tied');m.scoreA=a;m.scoreB=b;m.winnerTeamId=a>b?m.teamAId:m.teamBId;m.status='complete';m.completedAt=now();m.board=m.board||clean(input.board);log(db,'match.result',m.id,{scoreA:a,scoreB:b,winnerTeamId:m.winnerTeamId});maybeAdvance(db,m.eventId);assignBoards(db,m.eventId);await save(db);return director(m.eventId,db)}
export async function resetMatch(matchId){const db=await load(),m=db.matches.find(x=>x.id===matchId);if(!m)throw new Error('Match not found');const later=db.matches.filter(x=>x.eventId===m.eventId&&x.round>m.round);if(later.some(x=>x.status==='complete'))throw new Error('Cannot reset after a later-round result has been completed');db.matches=db.matches.filter(x=>!(x.eventId===m.eventId&&x.round>m.round));m.status='queued';m.scoreA=0;m.scoreB=0;m.winnerTeamId=null;m.completedAt=null;m.board='';const e=db.events.find(x=>x.id===m.eventId);if(e){e.status='running';delete e.championTeamId}assignBoards(db,m.eventId);log(db,'match.reset',m.id);await save(db);return director(m.eventId,db)}

function placements(db,eventId){const e=db.events.find(x=>x.id===eventId);const ms=db.matches.filter(x=>x.eventId===eventId);if(!e||e.status!=='complete')return[];const maxRound=Math.max(...ms.map(x=>x.round));const final=ms.find(x=>x.round===maxRound);const out=[];if(final?.winnerTeamId)out.push({place:1,teamId:final.winnerTeamId,points:e.pointsScheme.first});const runner=final?.winnerTeamId===final?.teamAId?final?.teamBId:final?.teamAId;if(runner)out.push({place:2,teamId:runner,points:e.pointsScheme.second});for(const m of ms.filter(x=>x.round===maxRound-1)){const loser=m.winnerTeamId===m.teamAId?m.teamBId:m.teamAId;if(loser)out.push({place:3,teamId:loser,points:e.pointsScheme.third})}const placed=new Set(out.map(x=>x.teamId));for(const t of db.teams.filter(x=>x.eventId===eventId))if(!placed.has(t.id))out.push({place:null,teamId:t.id,points:e.pointsScheme.participation});return out}
export async function director(eventId,provided){const db=provided||await load(),e=db.events.find(x=>x.id===eventId);if(!e)throw new Error('Tournament not found');return {event:e,entrants:db.entrants.filter(x=>x.eventId===eventId),teams:db.teams.filter(x=>x.eventId===eventId),matches:db.matches.filter(x=>x.eventId===eventId).sort((a,b)=>a.round-b.round||a.slot-b.slot),placements:placements(db,eventId),audit:db.audit.filter(x=>x.entityId===eventId||x.detail?.eventId===eventId).slice(0,50)}}
